### ISSUE TITLE
Create a legacy configuration property to map COUNT as INTEGER instead of BIGINT [CORE5514]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#5783]
Submitted by: Beto Neto (betoneto.tbo)

Votes: 1

Create a legacy configuration property to map COUNT as INTEGER instead of BIGINT in firebird\.conf\.

**Comment by dyemanov** [comment]
SET BIND is not a solution for this task as it covers only new data types but INT64 is available since IB6.

I expect all existing connectivity drivers / components to finally support INT64 now. Those who still don't ... well, shame on them, but it's not our problem. I tend to close this ticket as won't fix.

**Comment by AlexPeshkoff** [comment]
Sorry, set bind perfectly works with old datatypes:

SQL> select count(*) from country;
INPUT message field count: 0
OUTPUT message field count: 1
01: sqltype: 580 INT64 scale: 0 subtype: 0 len: 8
  :  name: COUNT  alias: COUNT
  : table:   owner: 

                COUNT 
===================== 
                   16 

SQL> set bind of bigint to int;

SQL> select count(*) from country;
INPUT message field count: 0
OUTPUT message field count: 1
01: sqltype: 496 LONG scale: 0 subtype: 0 len: 4
  :  name: COUNT  alias: COUNT
  : table:   owner: 

       COUNT 
============ 
          16 

But this is one more reason to close this item w/o fix.
