### ISSUE TITLE
"LIKE" queries should use expression index if expression uses system functions e.g. UPPER [CORE6079]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#6329]
Submitted by: @livius2

CREATE TABLE NAMES
\(
NAME VARCHAR\(100\)
\);
commit;
INSERT INTO names
SELECT RF\.RDB$FIELD\_NAME FROM RDB$RELATION\_FIELDS RF;
commit;
CREATE ASCENDING INDEX IXAE\_NAMES\_\_NAME ON NAMES COMPUTED BY\(UPPER\(NAME COLLATE PXW\_PLK\)\);
commit;

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

SELECT \* FROM NAMES N WHERE UPPER\(<http://N.NAME> COLLATE PXW\_PLK\) LIKE 'RDB%SYSTEM\_FLAG%' 
PLAN \(N INDEX \(IXAE\_NAMES\_\_NAME\)\)
this works as expected

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
SELECT \* FROM NAMES N WHERE UPPER\(<http://N.NAME> COLLATE PXW\_PLK\) LIKE UPPER\('RDB%SYSTEM\_FLAG%'\)
PLAN \(N NATURAL\)

but this one not \- because of function used in LIKE pattern\.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

I understand current logic, because someone can use custom function and change order of characters\.
But system function UPPER does not change anything in like pattern, and index still can be used\.
I do not know which other \(only system\) functions can be used this way but UPPER and LOWER are obvious one\.

**Comment by dyemanov** [comment]
This is not about expression indices, but about indices in general. `LIKE` can use an index only if it can be converted into `STARTING` which in turn can happen only if the pattern does not start with a wildcard. Currently, the engine may check this only if the pattern is a string literal, because it's simple. I agree that `LOWER/UPPER` do not change the order of characters so we could look one level deeper. Another "special cases" could be `LEFT`, `RPAD` and maybe even `SUBSTRING` with `startpos == 1` and `length > 1`. But for me checking for such exceptions look somewhat fragile.

**Comment by dyemanov** [comment]
Looks like #7912 may be a better solution, if implemented. Closing in favour of the newer ticket?

**Comment by mrotteveel** [comment]
@dyemanov I'd say yes, but I'm biased ;)
