### ISSUE TITLE
A way for a replication plugin to refuse attachment [CORE6540]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6767]
Submitted by: @aafemt

If it is not too late the signature of IReplicatedSession::setAttachment\(\) should be changed to "bool setAttachment\(Status status, Attachment attachment\)" to let replication plugin refuse replication of this attachment for any reason \(configuration option, "bad" user name, etc\) with an optional error message\.

**Comment by dyemanov** [comment]
Do you mean that the optional message is taken from the status argument and printed to the log? This may be OK only if a warning is returned (and log_errors is enabled in the config). If error is returned, this would be a critical "no-go" condition (as for any other errors).

So I have no problems adding a status and making the method returning bool, so that it would behave similar to startTransaction() -- i.e. false result without error in the status means silently disabled replication for this attachment. If warning is present in the status, then it will be logged (if configured).

Also, if we agree on the rules above, then perhaps this method should better be renamed to something like initialize().

**Comment by aafemt** [comment]
>  I have no problems adding a status and making the method returning bool, so that it would behave similar to startTransaction() -- i.e. false result without error in the status means silently disabled replication for this attachment. If warning is present in the status, then it will be logged (if configured).

This is exactly what I had on mind.

> Also, if we agree on the rules above, then perhaps this method should better be renamed to something like initialize().

Best of all would be add the attachment to parameters of plugin's factory but whole current plugin architecture is against it.
