### ISSUE TITLE
Conflicting INSERT propagated into a read-write replica may cause duplicate records to appear (and PK/UK violation to happen)

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#6849]
Imagine a table T declared as (ID INT PRIMARY KEY, COL INT) with one record (1, 1). This table is identical between primary and replica databases. Then a new record (2, -2) is inserted into the replica database. Then a new record (2, 2) is inserted into the primary database. Conflict happens and detected (see replication.log):

> 	Database: /data/repl.fdb
> 	WARNING: Record being inserted into table T already exists, updating instead

However, instead of the record (2, -2) being overwritten with (2, 2) replicated from the primary side, we see the following contents for table T:

```
          ID          COL 
============ ============ 
           1            1 
           2           -2 
           2            2 

```
which is surely not expected and practically nonsense (read: definitely buggy).

**Comment by pavel-zotov** [comment]
::: test details :::
SWEEP must be done both on master and replica at the final point of this test.
Otherwise replication gets stuck on the second run of this test with message 
"ERROR: Record format with length 68 is not found for table TEST".
The reason was explained by dimitr privately. Fix for this will be later.
