### ISSUE TITLE
Escape character with SIMILAR TO and insensitive collation works different than LIKE

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#6888]
With `LIKE`, escape character in pattern does not need to be identical:

```
SQL> select '%a' collate unicode_ci like 'Z%a' escape 'z' from rdb$database;
       
======= 
<true>  
```

In `SIMILAR` it need to be identical:

```
SQL> select '%a' collate unicode_ci similar to 'Z%a' escape 'z' from rdb$database;
        
======= 
<false> 
```

**Comment by mrotteveel** [comment]
I don't think the current behaviour for `LIKE` is correct. When using the escape clause, you define the specific character to use as an escape. That shouldn't be handled case insensitively IMHO. The case-insensitivity should only concern the actual comparison operation.

**Comment by asfernandes** [comment]
> I don't think the current behaviour for `LIKE` is correct. When using the escape clause, you define the specific character to use as an escape. That shouldn't be handled case insensitively IMHO. The case-insensitivity should only concern the actual comparison operation.

I see nothing in the standard that makes clear what is the correct.

And they are now inconsistent.

Also, in v3 `SIMILAR` worked as `LIKE`, so I think it's more logical to change `SIMILAR`.

**Comment by asfernandes** [comment]
> I don't think the current behaviour for `LIKE` is correct. When using the escape clause, you define the specific character to use as an escape. That shouldn't be handled case insensitively IMHO. The case-insensitivity should only concern the actual comparison operation.

Please note that LIKE (not talking about ESCAPE) is case-sensitive, but with insensitive collation it's insensitive. So seems logical for me that escape is also checked insensitive in this case.

**Comment by mrotteveel** [comment]
The fact the comparison performed by `LIKE` (or `SIMILAR`) would be case-insensitive, does in no indicate that the escape character would be case-insensitive as well. The escape clause defines the specific character you use to escape. That is 1 and only 1 **character** (mind you, I myself would never choose a letter as escape character...)

I think the general rules in 8.5 \<like predicate>, 3b make clear that the escape should be case-insensitive, because they speak about _"is the escape character ECV"_. Even in case-insensitive collations, `'A'` and `'a'` are not the same character, they are only considered equal in the comparison.

**Comment by asfernandes** [comment]
Ok @mrotteveel. I will close this issue and create another one for `LIKE`.
