### ISSUE TITLE
EXECUTE STATEMENT - PASSWORD should be optional in some case

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#6899]
Hi!

When a client is conneted both to database A and to database B with the same user/pw, then using EXECUTE STATEMENT ON EXTERNAL between A and B database should not require PASSWORD when same user used to connect (by not using AS USER part, or using same user)

Thank You!

**Comment by AlexPeshkoff** [comment]
Presence of client connections can't be taken into an account - server does not know about them, and even if it could get such info it's not secure to trust it. If A & B are on the same server one can just omit both AS USER & PASSWORD and that works since arrival of ON EXTERNAL clause. What about connecting different servers - take a look at fbSampleExtAuth plugin in FB4.
