### ISSUE TITLE
IBatch add method fails silently when a memory limit is exceeded

### ISSUE THREAD

**Issue by tony062017** [FirebirdSQL/firebird#6900]
I have been testing the Firebird 4 IBatch interface, and ran a stress test to see how quickly a large dataset could be created. The test table is defined as:

Create Table LotsOfData (
    RowID integer not null,
    theDate TimeStamp,
    MyText VarChar(1024),
    Primary Key (RowID)
  ); 

I used IBatch to add rows one at a time, and the test was set up to add 100K rows. At the end of the test, the batch completion interface was checked and the transaction committed. The table was then read back in order to verify read/write. An MD5 checksum on data in and data out was used to verify no data loss or corruption.

The test result showed that only 4061 records were written to table. This figure was reported both by the Batch Completion interface and on read back. However, no errors were reported at any time. The IBatch add interface status vector was checked on every call as was the execute. In both cases no error reported. The batch completion report "No More errors" for every row up to and including row 4061.

It seems that this a silent failure. An error should be reported either in the status vector (on IBatch::Add - the ideal solution) on in the batch completion.

Note that changing the test table to

Create Table LotsOfData (
    RowID integer not null,
    theDate TimeStamp,
    MyText VarChar(512),
    Primary Key (RowID)
  );

resulted in 8083 rows being successfully written.

**Comment by AlexPeshkoff** [comment]
[batch.zip](https://github.com/FirebirdSQL/firebird/files/6861445/batch.zip)
Tony, certainly size of batch is limited. Moreover, that limit can be changed using TAG_BUFFER_BYTES_SIZE in batch parameters block when starting batch.

**Comment by tony062017** [comment]
Alex,
I have run your example - and yes it works. However, it accesses the database as a local database. If you change the connect string to 'inet://localhost/employee' then the exception is not raised when buffer overflow occurs. It looks like there is different behaviour with local and remote databases.

**Comment by tony062017** [comment]
Also, when the buffer overflow occurs, I am seeing error isc_dsql_error  (335544569) rather than then expected isc_batch_too_big = (335545198).

**Comment by AlexPeshkoff** [comment]
Got you, will check 

Sent from MailDroid

**Comment by AlexPeshkoff** [comment]
Reproduced on remote server, embedded is OK

**Comment by tony062017** [comment]
I have tested the fix with both the embedded and remote server and there is still a difference. The bug does not yet appear to be fixed.

The tests were conducted with a Firebird installation built from source code downloaded from github (master branch) after the fix was reported. Using the example cpp program, the "-Internal buffer overflow - batch too big" error is reported 

after row 7936 is written with the remote server, and
after row 2 is written with the embedded server.

I have also tested the fix with my IBX test suite. This test aims to stress test the server with IBatch and also to recover from a buffer overflow ( a cut down version for 10000 rows is shown). When using the embedded server the follow output is recorded:

Running Test 20: Stress Test IBatch interface
 FBVersion = Firebird/Linux/AMD/Intel/x64 (access method), version "LI-T5.0.0.139 Firebird 5.0 Initial"
Intermediate Apply Batch on row 4085 status code = 335544569
Batch Completion Info
Total rows processed = 4084
Updated Rows = 4084
Row 4084 State = bcNoMoreErrors Msg = 
Intermediate Apply Batch on row 8169 status code = 335544569
Batch Completion Info
Total rows processed = 4084
Updated Rows = 4084
Row 4084 State = bcNoMoreErrors Msg = 
Batch Completion Info
Total rows processed = 1832
Updated Rows = 1832
Row 1832 State = bcNoMoreErrors Msg = 
Rows in Dataset = 10000
 Message Hash = 0eb2c88e5913ebfec1105e9f96c6b0f0
 Message Hash = 0eb2c88e5913ebfec1105e9f96c6b0f0
Test Completed Successfully

Note the intermediate calls to IBatch::execute. These occur after each buffer overflow exception and write the current buffer to the database. 

E.g. The first exception occurs when adding row 4085. The buffer contains 4084 rows which are then written to the database, and so on.

A new batch is created after each such exception and the row on which the exception occurred is added as the first row in the new batch and the iteration continues. At the end, the last batch is written to the database. A message hash is computed as each row is added to the batch. The "Rows in Dataset" line reports the result of a "select count(*)..." query and confirms that 10000 rows were written. The table is then read back in using a select query and the hash recomputed. These match indicating that the test was successful and all rows were correctly written to the database.



The test is then run again with the connect string changed to inet://localhost/... This results in the following output:

Running Test 20: Stress Test IBatch interface
 FBVersion = Firebird/Linux/AMD/Intel/x64 (access method), version "LI-T5.0.0.139 Firebird 5.0 Initial"
Intermediate Apply Batch on row 5921 status code = 335544569
Batch Completion Info
Total rows processed = 4061
Updated Rows = 4061
Row 4061 State = bcNoMoreErrors Msg = 
Batch Completion Info
Total rows processed = 4080
Updated Rows = 4080
Row 4080 State = bcNoMoreErrors Msg = 
Rows in Dataset = 8141
 Message Hash = 0eb2c88e5913ebfec1105e9f96c6b0f0
Test Fails - expecting 10000 rows - found 8141
 Message Hash = 8e7323ad002564fa0472506a1d3ec12d
Test Failed - MD5 checksum error

Note that the first buffer overflow exception now occurs on row 5921. However, the batch completion info reports that only 4061 rows were actually written. This should have been 5920. The test resumes and the remaining 4080 rows appear to then be successfully written. However, the select queries confirm that only 8141 rows are present. The remainder have been lost.

There is still a clear difference in the behaviour of the embedded server and the remote server and the bug needs to be re-opened. 

It is also unclear why the second word of the status vector is returning 335544569 rather than the expected 335545198.

**Comment by AlexPeshkoff** [comment]
Returning isc_batch_too_big not at once is normal and documented behavior. It takes place due to buffering messages on the client and replies to them on server. Without that buffering batch will loose performance almost to running inserts/updates sequentially. From Using_OO_API: JDBC does not recommend to use too large batches, for example "Oracle recommends you to keep the batch sizes in the general range of 50 to 100”. Firebird supports bigger batches but it anyway has to limit maximum batch size – see TAG_BUFFER_BYTES_SIZE. If total size of messages exceeds that limit isc_batch_too_big error is returned. Pay attention that due to deep buffering of batch data when sending it over the wire you will not get this error at once but only when buffers are flashed from client to server. This may happen in both add() and execute() methods – execute() performs final flash. If you still wish to execute the batch with the messages that fit in a buffer you may do it (when error was returned by execute() just repeat it). An actual number of processed messages will be returned in BatchCompletionState.

Previous behavior when message addition might proceed unlimited before execute() was certainly bad but I do not see great problems with current. The only way to avoid it completely is to turn off buffering which will kill performance. I try to predict next question - why not take into an account that limit on client and stop when number of messages reaches it? Currently it's possible but in the future we have plans to switch to variable message length (including unlimited char/varchar fields and maybe messages compression) and such prediction becomes impossible, specially when using different versions of client and server.

**Comment by AlexPeshkoff** [comment]
What about the second question - isc_batch_too_big is not primary error code, therefore it's not in the second word of status vector.

**Comment by tony062017** [comment]
So, I think what you are saying is that a buffer overflow error implies an unpredictable number of row losses - i.e. not just the one on which the IBatch::add fails. If you execute the batch following such an error, then the application has to check the batch completion in order to determine what has been lost.

**Comment by tony062017** [comment]
> What about the second question - isc_batch_too_big is not primary error code, therefore it's not in the second word of status vector.

I guess what you are saying here is that the error code is further down the status vector. Where is this documented? I have alwways assumed that the status vector is unchanged since the InterBase 6 API Guide.

**Comment by AlexPeshkoff** [comment]
Looking better at isc_batch_too_big I agree that it has nothing to do with traditional DSQL errors and should be primary, fix is committed.

**Comment by AlexPeshkoff** [comment]
> If you execute the batch following such an error, then the application has to check the batch completion in order to determine what has been lost.

Yes, and this works for both network and embedded connections.

**Comment by aafemt** [comment]
It is not clear for me why IBatch::add() following after IBatch::execute() replaces remaining content of buffer instead of appending messages to it.

**Comment by tony062017** [comment]
> It is not clear for me why IBatch::add() following after IBatch::execute() replaces remaining content of buffer instead of appending messages to it.

It doesn't. In my test program, a new batch is created after the execute and the row appended to the new (empty) batch.

**Comment by AlexPeshkoff** [comment]
Yes, it's not trivial. The reason is that not only messages sent to 
server are buffered but also replies from server to them. That's pretty 
efficient for WANs with a lot of routers on the way between client and 
server - client need not wait for reply for a every single packet 
transfered to server. Only after sending some (currently fixed value == 
64) buffers full of data (currently each 128Kb) batch performs sync with 
server in order to check for buffer overflow. In order to be able to 
restart client should keep all that records somewhere. On the other hand 
8Mb is not big value today... May be it's really worth to go this way?

**Comment by tony062017** [comment]
I think I understand better what is going on now. My assumption is that when the client side buffer fills up, you get a buffer overflow exception. However, you are saying that the client side buffer, when it fills up, is copied to the server. The buffer is then cleared and more rows can then be added. On the server side, the unapplied buffers can accumulate until some limit is reached, when the exception is raised.

I modified my test so that it did not create a new batch when the exception occurred, hoping that the client side buffer still had the (lost) rows in it. However, there was no change in the output, so I assume that the buffer is cleared before the exception is returned by the server.

Question: why not enable a bigger buffer client side and raise the exception when it overflows? This should allow my recovery strategy to work.
