### ISSUE TITLE
Failed DDL commands can be replicated.

### ISSUE THREAD

**Issue by iprenosil** [FirebirdSQL/firebird#6907]
When adding new NOT NULL column to table containing data, Firebird will raise error
"Cannot make field F of table T NOT NULL because there are NULLs present"
However this command is replicated. In replication.log there is
  ERROR: unsuccessful metadata update
  Cannot make field F of table T NOT NULL because there are NULLs present

Tested with FB4.0 Final and Firebird-4.0.1.2538-0_x64 (snapshot 2021-07-24)

**Comment by dyemanov** [comment]
@aafemt, this is exactly the failure case I told you about after you committed 2PC. Early DFW replication makes sense for the sync mode (to execute the heavy work in parallel), but is absolutely useless (and actually painful, as this example shows) for the async mode. I can think of two solutions:

**Comment by aafemt** [comment]
First solution seems logical to me but still I would go to moving the check from DFW into DML.
When I committed 2PC I could not imagine that you write the command to the log because I supposed IReplicatedTransaction::prepare() to do only flush of the log (and do other work that ensure the "final commit" to run flawlessly).

The only thing I doubt about: is failed DFW work removed from queue? If yes, then the transaction may be committed after all and it will end up in another problem.
