### ISSUE TITLE
Dialect 3 inconsistent round/trunc

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#6928]
Hi *!

127.13 / 3.4618 = 36,72366976717315

EXECUTE BLOCK
RETURNS (
    c0 NUMERIC(15,10),
    c1 NUMERIC(15,10),
    c2 NUMERIC(15,6),
    c3 NUMERIC(15,5),
    c4 NUMERIC(15,4))
AS
DECLARE VARIABLE a NUMERIC(15,2);
DECLARE VARIABLE b NUMERIC(15,4);
BEGIN
  a = 127.13;
  b = 3.4618;
  c0 = a / CAST(b AS DOUBLE PRECISION);--36,7236697672, this is OK
  c1 = a / b;--36,7236690000, this shoud be 36,7236700000
  c2 = a / b;--36,723669, this shoud be 36,723670
  c3 = a / b;--36,72367, this is OK
  c4 = a / b;--36,7237, this is OK
  SUSPEND;
END

If return variable scale is bigger or equal than operation result scale, then computed value is truncated, but when return variable scale is smaller than operation result scalethen computed value is rounded.

I think in all case value should be rounded, this behaviour is inconsistent, and also truncation is unexpected behaviour.
I tried to found some documentation for this behaviour but found nothing.

**Comment by mrotteveel** [comment]
The result of the division between a NUMERIC(15,2) and NUMERIC(15,4) is a NUMERIC(18,6), so the result of  36,723669(0...) is correct. The division completes when the sixth decimal digit is calculated. There is no rounding involved. You seem to expect that the calculation is done using floating point semantics like it was in dialect 1.

However, this is not how division in dialect 3 works.

**Comment by EPluribusUnum** [comment]
@mrotteveel , than dialect 3 is useless, if it changes the calculation precition itself, not just the result storage. In this case please consider keeping dialect 1 support forever (do not depreacte and remove), or create a new dialect, where calculation is always precise and dialect just affects the storage. 
Please repoen the issue, this is mayor probem, and needs a proper discussion.
BTW this should be documented properly.
Thank you!

**Comment by mrotteveel** [comment]
@EPluribusUnum The dialect 3 behaviour of divide has been this way since InterBase 6.0. This difference between dialect 1 and 3 is well-known (and one of the reasons some users still prefer dialect 1). If you want similar behaviour in dialect 3, then you need to cast one or both of the operands to `double precision`.

If you want to discuss retention of dialect 1, then please take that to firebird-devel.

**Comment by aafemt** [comment]
Perform calculations on server side is a bad design in any case.

**Comment by mrotteveel** [comment]
Note the firebird-devel list has been moved to https://groups.google.com/g/firebird-devel

**Comment by dyemanov** [comment]
I see that both MSSQL and PGSQL return 36,723670 for your third example. I can understand why it happens and actually I believe we may do the same (at least optionally, to please backward compatibility). However, if done this way, the second example should return 36,7236697672 because it fits NUMERIC(15,10). And I can confirm that result with both MSSQL and PGSQL. So I'm afraid your expectations are somewhat contradictory.
