### ISSUE TITLE
Firebird freeze

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#6982]
Hi!

Sometimes FB freeze. When this happens no new connection can be established, you must restart the FB server.
I made a ProcDump (FB 2.5.9, superclassic, x64) file, and uploaded our FTP server. The zip also contais all SQL executed by the program which leads to the freeze. (log does not contains SQL executed by Jaybird)
The freeze not always happens, which suggest it's a concurrency issue, but the SQL-s runs on a single thread on client side. No other application are attached during the run, this application uses many different connections to the DB.
From the SQL log we see that this freeze happens when the SQL has EXECUTE STATEMENT ON EXTERNAL call, so it might be that Firebird connection handling/connection pool is prone to deadlock.
Also we have this on FB30 and FB40. I'll try to get a dump for them also.
(Now we are experimenting with 100ms sleep after transaction rollbacks, looks like this helps to avoid the deadlock)

FTP: ftp://ftp.mve.hu
user: firebirdproject
pass : I'll send you in private on request.
file: fbfreez_procdump.zip

Thank you!

**Comment by AlexPeshkoff** [comment]
On 9/23/21 5:31 PM, EPluribusUnum wrote:
>
> Hi!
>
> Sometimes FB freeze. When this happens no new connection can be 
> established, you must restart the FB server.
> I made a ProcDump (FB 2.5.9, superclassic, x64) file, and uploaded our 
> FTP server. The zip also contais all SQL executed by the program which 
> leads to the freeze. (log does not contains SQL executed by Jaybird)
> The freeze not always happens, which suggest it's a concurrency issue, 
> but the SQL-s runs on a single thread on client side. No other 
> application are attached during the run, this application uses many 
> different connections to the DB.
> >From the SQL log we see that this freeze happens when the SQL has 
> EXECUTE STATEMENT ON EXTERNAL call, so it might be that Firebird 
> connection handling/connection pool is prone to deadlock.
>
> FTP: ftp://ftp.mve.hu
> user: firebirdproject
> pass : I'll send you in private on request.
> file: fbfreez_procdump.zip
>

Version 2.5 is not supported any more, is your issue reproducible on FB4?

**Comment by EPluribusUnum** [comment]
Yes, this is also an issue in FB30 and FB40. I'll try to get a dump for them also.

**Comment by EPluribusUnum** [comment]
You can find FB3.0.7 and FB4.0.0 (superclassic x64) proc dump on FTP.

**Comment by AlexPeshkoff** [comment]
>> pass : I'll send you in private on request.

How to contact you privately?

**Comment by EPluribusUnum** [comment]
@AlexPeshkoff , just sent your gmail address the FTP password.

**Comment by hvlad** [comment]
I've analyzed FB 3.0.7 dump and it looks like complex deadlock with two databases and EXECUTE STATEMENT's involved.

Thread 13 is attaching to the database DB1 (I prefer to not show sensitive names in public) and run ON CONNECT trigger.
This trigger want to update record in table TAB_A. The record is updated by currently active transaction 100949.
Current transaction (100951) is in WAIT mode and waits for finish of transaction 100949.

Thread 6 already attached to the database DB1 and run transaction 100949.
This transaction updated record in table TAB_A earlier, obviously.
Currently it executes stored procedure that run external statement on database DB2.
The statement is "update TAB_B ...". 
The thread is waiting for response from remote side.

Thread 11 is attached to the database DB2 and run "update TAB_B ..." statement.
Currently it executes AFTER trigger that executes SP_1 that executes SP_2 that run external statement
on database DB1 and tries to attach to database. 
The thread is waiting for response from remote side also.

So, thread 13 waits for thread 6, that waits for thread 11, that waits for thread 13 - this is deadlock.
@EPluribusUnum - if you wish, I could show real names of objects involved.

I see no problem at Firebird side here, i.e. nothing to fix. 
The issue is at application logic.

**Comment by EPluribusUnum** [comment]
@hvlad , thank you! No need for real object names, I can understand this was also.
Does this means, that ON CONNECT transaction is a WAIT transaction? I see nothing in documentation related to on connect trigger transaction parameters. Can I control the transaction parameters somehow, eg, connection string parameter?
(On the client side we always use NO WAIT for transasctions.)

**Comment by hvlad** [comment]
> 
> 
> Does this means, that ON CONNECT transaction is a WAIT transaction? 

Yes, default parameters are used (concurrency, write, wait).

> I see nothing in documentation related to on connect trigger transaction parameters. 

Feel free to ask documentation team to add this info.

> Can I control the transaction parameters somehow, eg, connection string parameter? 

No, sorry.

**Comment by EPluribusUnum** [comment]
Done: https://github.com/FirebirdSQL/firebird-documentation/issues/163

Thank you for your help.
