### ISSUE TITLE
FB service hangs and can not be stopped after several 'DELETE FROM MON$STATEMENTS' being issued in order to stop ES/EDS which waits record for updating

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7103]
[fb-service-can-not-be-stopped-when-trying-to-del-from-mon$statements-es-eds.zip](https://github.com/FirebirdSQL/firebird/files/7880118/fb-service-can-not-be-stopped-when-trying-to-del-from-mon.statements-es-eds.zip)
1) replace firebird.conf with following:
```
BugcheckAbort = 1
FileSystemCacheThreshold = 65536K
Servermode = Super
DefaultDbCachePages = 5000
TempBlockSize = 2M
TempCacheLimit = 2147483647
LockHashSlots = 22111
LockMemSize = 5M
AuthClient = Srp, Srp256, Win_Sspi, Legacy_Auth
AuthServer = Srp, Srp256, Win_Sspi, Legacy_Auth
UserManager = Srp, Legacy_UserManager

WireCompression = false
WireCrypt = Enabled
```
2) unpack files from attached .zip and open 'eds-hang.bat' in editor; change there variables:
```
set FB_HOME=C:\FB\40SS
set ISC_USER=SYSDBA
set ISC_PASSWORD=masterkey
```
3) ensure that databases.conf contain alias 'employee' for built-in FB example database; 
4) stop any running FB instances and applications; launch selected firebird (3.x, 4.x or 5.x) as service
5) run batch eds-hang.bat 

After several iterations (number can vary, but usually it will be less than 30) console will hang with somewhat like this:
```
17.01.2022 10:14:48.74 Starting C:\FB\50SS\isql localhost:employee -i eds-hang.sql 1>>C:\FBTESTING\qa\misc\eds-hang.1.log 2>&1
17.01.2022 10:14:48.74 Take small delay, point-1...
17.01.2022 10:14:50.75 Trying to delete from mon$statements, command:
echo set count on; delete from mon$statements where mon$attachment_id is distinct from current_connection; | C:\FB\50SS\isql localhost:employee
```
Since that moment FB service can not be stopped via NET STOP or services.msc GUI; only termination like  "taskkill /f /t /im firebird.exe" can solve this problem.
Note that this can be reproduced only when we try to delete record from MON$STATEMENTS. No such problem with MON$ATTACHMENTS.

Checked on: WI-V3.0.9.33548; WI-V4.0.1.2704; WI-T5.0.0.372

**Comment by pavel-zotov** [comment]
PS.
Dumps + stack traces:
https://drive.google.com/drive/folders/1WNnUwv5O9jtAaXlQrFpDRR_s2W6SZk4E

**Comment by hvlad** [comment]
External attachment receives signal to cancel activity two times: by monitoring system and when user attachment receives own signal to cancel and cancels execution of external query.

The problem is that sometime one of the signals might be seen and handled after the query cancellation and breaks next API call, in this case - rollback. Thus, external connection doesn't rollback own transaction and later detach is failed. Metadata locks is kept by that orphan external connection and doesn't allow next connection to re-create table. 

Fully correct solution would be to re-architect `fb_cancel_operation()` API to avoid wrong cancellation of action that happens after expected one (rollback() instead of execute() in our case). For now, I'll commit workaround to fix this particular case.
