### ISSUE TITLE
Avoid unload of plugins in MacOS due to problematic reload of them

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7112]
Due to usage of thread locals (`__thread`) variables and ObjC frameworks, MacOS do not unload libraries when calling dlclose.

That makes Firebird plugins in wrong state when the plugin manager tries to reload them and they are already loaded in the process memory.

**Comment by datiscum** [comment]
This is interesting because I have exactly the same problem with Lazarus/FPC compiled UDF/UDR under Linux. I would be particularly interested to know whether the bug fix is really effective. Under Linux/FPC it is exactly the same and is due to FPC, as a developer of FPC has confirmed. As well as it being a non-fixable problem. See my BUG report in FPC:
"https://gitlab.com/freepascal.org/fpc/source/-/issues/39531" . The problem is, but much more far-reaching. It is deceptive to think that you can simply ban unloading and all is well. Since problems can also arise from excessive parallel use of the library. I can only say for sure for FPC at the moment, but it will probably affect other languages as well. If I expose exactly this library with the unloading problem to massive multitasking, there will inevitably be other runtime errors as well. 
Here's what the FPC library caused with 20 concurrent test processes in the Firebird Superserver.CPU load approx. 430%.
1. /opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated abnormally (-1)
2. /opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated abnormally (255)
On the client side, errors can also occur that are hardly comprehensible, e.g. "Invalid blob handle".

All these errors do not happen if you test them with only one process and Firebird does not access the library with several threads. As I wrote in the BUG Report for FPC, there are no such problems with the UDF written in C under Linux.
So you might not get such problems with classic/embedded either. 
The starting point for the search for the bug was a weekly crash of Firebird when the last database connection was closed for maintenance and too much time passed until the new one was re-established.
Log from the server:
[Sun Oct 17 20:36:56 2021] firebird[13139]: segfault at 7f155b716f30 ip 00007f155b716f30 sp 00007f1503ecae28 error 15
[Sat Oct 23 22:53:27 2021] firebird[1480]: segfault at 7f61f6be4f30 ip 00007f61f6be4f30 sp 00007f61ce070e28 error 14
[Sun Nov 21 16:48:21 2021] firebird[13608]: segfault at 7efd5175bf30 ip 00007efd5175bf30 sp 00007efd9892ce28 error 14

It takes about 1-2 minutes for the server to crash after the UDF has been unloaded, because it does not crash when the UDF is unloaded, but when the Firebird module that loaded the UDF/UDR is unloaded.
To save many people problems, the Firebird quality assurance team should address this issue and produce sensible documentation on what not to use to create a UDF/UDR. The problems are likely to be largely seen as bugs in Firebird, although they are due to such external eye-opening libraries.

I hope I could help someone with this comment.
It took me several days to reproduce this problem 100% and understand that the crash is not due to Firebird itself.

**Comment by aafemt** [comment]
What you describes has nothing to do with this issue and indeed caused by bug in FPC.

**Comment by datiscum** [comment]
The symptoms are the same and I did not claim that it has to be exactly the same problem. It is also to be understood as a hint when it comes to problems with UDF/UDR. I also found this thread by searching, which is now supplemented by the problems with FPC.
If you are absolutely sure that it works with multitasking access on the Mac, it is wonderful.

**Comment by aafemt** [comment]
Once again: this issue has nothing to do with multitasking and has none of symptoms you are describing.

**Comment by aafemt** [comment]
PS: Your bug is most likely caused by known problem with default FPC memory manager in multithreading mode. The workaround it to switch to cmem: https://wiki.freepascal.org/CMem

**Comment by datiscum** [comment]
You should read the post carefully, I already use cmem.
I have read the documentation!
And if a main developer confirms the problem and also classifies it as unsolvable, he hoofentlich has enough knowledge about the internal problems that hardly anyone else comes into contact with.

**Comment by datiscum** [comment]
Apparently, the developers of Firebird never thought too deeply about the UDF/UDR multitasking problems. In C/C++ it works perfectly.

**Comment by AlexPeshkoff** [comment]
On 1/29/22 14:29, datiscum wrote:
>
> Apparently, the developers of Firebird never thought too deeply about 
> the UDF/UDR multitasking problems. In C/C++ it works perfectly.
>

We use C++ - therefore yes, nobody thought too much about pascal 
specific. As for me, I've written my last pascal program in 1987.

**Comment by datiscum** [comment]
By the way, when I tested the supplied C++ sample UDR "libudrcpp_example.so", it was never unloaded again. Is it possible to specifically prevent the unloading of a UDR?

UDR were introduced to write triggers/functions and stored procedures from other programming languages. And the problems of the UDF also apply in exactly the same way to a UDR. It might be possible to introduce mechanisms in Firebird to use libraries with such problems.

**Comment by aafemt** [comment]
Isolating of UDR/UDFs to allow using bugged ones is possible but costly and thus pointless.

**Comment by datiscum** [comment]
However, loading all the required data into the client application and building the logic there can cost a lot more time, especially over slow connections. If it would be enough to prevent simultaneous calls to a UDF/UDR, the effort would probably not be very big ( one Lock ). If one considers now still how rarely in the productive operation at all problems occur (thus apparently simultaneous accesses occur) the speed is rather not the problem.

**Comment by aafemt** [comment]
No, the cost is exactly the same because isolating of an UDR requires a separate application that is run aside of server every time the UDR is invoked. To solve slow connection issue you can just put your application close to the server using three-tier or any other trick.
