### ISSUE TITLE
Ignore missing UDR libraries during restore

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7168]
We have this supported for UDFs since the first FB versions and it's quite handy, especially for developers/supporters dealing with user databases. It's not working for UDRs though, error is thrown during restore (_"UDR module not loaded"_). It would be nice to be able to restore such databases, with nullified module/node pointers and re-validate them before execution, similarly to how it's done for UDFs.

**Comment by asfernandes** [comment]
UDFs without their libraries, at least in recent versions, are allowed to be created even in the normal use (outside restore).

Should we do the same for UDRs?

**Comment by AlexPeshkoff** [comment]
Do we check for parameters match when create UDR?

**Comment by asfernandes** [comment]
> Do we check for parameters match when create UDR?

Please elaborate.

**Comment by AlexPeshkoff** [comment]
With UDF we have absolutely no ways to check for parameters match (and this is what a lot related vulnerabilities are using).
With UDR we can ensure that format of messages does match what UDR expects before calling it. I've never reviewed how and where are that checks organized but it's more or less obvious that for in some cases error to be raised: for example when one tries to cast floating point to boolean or number of fields in messages do not match.

If some of that checks are performed at create time then adding UDR without the library seems to be bad idea, otherwise - why not.
