### ISSUE TITLE
Issue with SYSDBA user and Legacy_Auth

### ISSUE THREAD

**Issue by tomaszdubiel18** [FirebirdSQL/firebird#7234]
Hello.
I'm not sure whether that's an improver behavior or user error. I will explain it below.
I install the latest Firebird 3.0 (OS independent issue). While installation I set non standard SYSDBA password. After that, I change those parameters:
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
UserManager = Legacy_UserManager, Srp
WireCrypt = Enabled 
and restart service.
After that, Legacy_Auth SYSDBA user was automatically created with standard password, I can log in with masterkey.
Is it expected behaviour?
On Windows I can already enable Legacy_Auth during installation and both SYSDBA users get the password I give while installation.
Should on Linux be dialog whether to enable Legacy_Auth? Or when enabling Legacy_Auth after installation, the Legacy_Auth SYSDBA user should get password of SRP SYSDBA user?
Or current behaviour is expected and everyone installing Firebird need to keep it in mind to manually change Legacy_Auth SYSDBA password?

**Comment by tomaszdubiel18** [comment]
Updated. Mentioned steps lead to the same effect on Windows.

**Comment by mrotteveel** [comment]
Yes, this is expected. The database contains a default entry for SYSDBA for the Legacy_Auth plugin. So, it is not that a SYSDBA account with masterkey was created after your steps, it already existed, but only became usable after you enabled Legacy_Auth.

This behaviour is also mentioned in the Firebird 3.0 release notes, under [Compatibility Issues, Initializing the Security Database](https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rlsnotes30.html#rnfb30-compat-initsec):

> This initialization is not required and should not be performed if you have configured the server to use legacy (pre-Firebird 3 style) authentication and user management. The legacy security plugins totally preserve the legacy behaviour and thus contain the legacy record for SYSDBA with “masterke” as the initial password.

I would strongly recommend switching the Srp instead of persisting to use Legacy_Auth.

This is something that is better asked on firebird-support than on our bug tracker.
