### ISSUE TITLE
READ COMMITTED READ CONSISTENCY mode is broken in Classic / SuperClassic on Linux (the newly created users are not visible to execute statement)

### ISSUE THREAD

**Issue by dmitry-starodubov** [FirebirdSQL/firebird#7255]
The script below works in 3.0 (all architectures) and in 4+ (Supersever only). But 4+ Classic and Superclassic on Linux fail with the error "Your user name and password are not defined. Ask your database administrator to set up a Firebird login.".
Although it will work fine if we wait 10 seconds before execute block.
```
create user test password 'test';
commit;

set term ^;
create or alter procedure sp_main(a_usr varchar(31), a_pwd varchar(31))
  returns(x int) as
begin
  for
          execute statement
          'select 1 from rdb$database'
          as user a_usr password a_pwd into x
  do
          suspend;
end
^
set term ;^
commit;

grant execute on procedure sp_main to test;
commit;

-- wait 10 seconds and it will work

set term ^;
execute block returns(x int) as
begin
  for execute statement ('select * from sp_main(:u, :p)') ( u := 'test', p := 'test' )
  into x
  do suspend;
end
^
set term ;^
commit;

drop user test;
commit;
```

**Comment by AlexPeshkoff** [comment]
Confirmed an issue

**Comment by AlexPeshkoff** [comment]
Renamed issue because actual error has much wider scope

**Comment by pavel-zotov** [comment]
QA issue: see notes in the test.

**Comment by VerbovenBerg** [comment]
@AlexPeshkoff @pavel-zotov 
Is it possible that a (variant to) this issue exists in Firebird 4.0.5 Classic (linux)?
We have 2000+ Firebird 4-databases, checking backup-restore every night and sporadically 10 (sometimes less) database-restores fail due to unmet constraints in the backup.
Duplicate records dissapear after being fetched, afterwards backup-restore is ok again.
We are trying to reproduce and pinpoint the issue but without success since the problem just occurs in rare cases.
(also nothing in firebird-logs)

**Comment by AlexPeshkoff** [comment]
Exactly this issue can not happen on windows - the bug was caused by different rules of files removing between linux & windows, and code was initially tested on windows.

Variants - hmm, in general that's certainly possible, but take into an account that gbak is not using RC transactions, it works with snapshot. I.e. sooner of all that's something different.

Please open new issue with description:
- what constraints fail, 
- what means 'after being fetched' here (gbak also fetches all records in database),
- and may be the most important - can you provide problematic database?
