### ISSUE TITLE
Change dependency from ncurses to libedit

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7305]
Some firebird utils (isql, gsec) need to use readline, but GPL license incompatible with BSD license.
Currently firebird linked with ncurses, but its version depend on linux distro.
Suggest link firebird with libedit (BSD license) in Fiebird5 and backport that into FB4, F3 and FB2.5.

**Comment by AlexPeshkoff** [comment]
You have an awful mix of libraries in this ticket. 

> Currently firebird linked with ncurses, 
That's wrong - any termcap-support library can be used (priority is curses, ncurses, termcap, tinfo). But this is detected at configure-time, i.e. library present at build machine will be always needed for everyone using binary package.

> but its version depend on linux distro.
> Suggest link firebird with libedit (BSD license) 

That's supported since FB1.5 or 2.0 - not sure exactly. Just do not use any related configure switches (or set explicitly --with-system-editline=no) - and BSD-licensed libedit will be used.

> in Fiebird5 and backport that into FB4, F3 and FB2.5.

Thanks god - not suggested to backport to FB1.0 :D
