### ISSUE TITLE
Removal of trigger/procedure source fails with error if source is already NULL

### ISSUE THREAD

**Issue by pcisar** [FirebirdSQL/firebird#7378]
Update to system tables is not allowed with one exception: setting trigger/procedure source to NULL. However, if source is already NULL, then update statement fails with: UPDATE operation is not allowed for system table <table>

How to reproduce:
Create procedure TEST and then run twice next SQL:

update RDB$PROCEDURES r set r.RDB$PROCEDURE_SOURCE = NULL
where r.RDB$PROCEDURE_NAME = 'TEST' ;

First execution passes, second fails.

**Comment by dyemanov** [comment]
This is not a bug and IIRC it was already discussed in the past. If the source is already NULL, you don't change anything in the record. But UPDATE is still performed, locking the record in system table. This may be done intentionally by some "bad guy", thus we prohibit dummy updates. The engine has no way to distinguish between setting source to NULL or changing some other field to itself. All you need to forget about this issue is to add `RDB$PROCEDURE_SOURCE IS NOT NULL` to the `WHERE` clause.

**Comment by dyemanov** [comment]
See also my comment in #4862
