### ISSUE TITLE
Backup error for wide table

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7436]
If table format width is close to 64Kb limit the following happens when gbak tries to write it's data to backup file:
   gbak: ERROR:message length error (encountered 32, expected 65568)

**Comment by AlexPeshkoff** [comment]
FB4 was not affected

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@

Currently only BACKUP succeeds in FB 5.x and 6.x.
RESTORE can be done only in FB 4.x and fails on FB 5.x/6.x ("expected record length / Exiting before completion due to errors")
Because of this, test is marked to be skipped for these major versions and executes only in FB 4.x
Sent report to Alex et al, 22.01.2024 10:07. Waiting for reply.

**Comment by pavel-zotov** [comment]
Restore works fine after commits 1dbcb940 and 37f19bf2. Test completed.

**Comment by mlazdans** [comment]
Any chance this fix will be applied to FB 3.0.x future version? Thanks!

**Comment by AlexPeshkoff** [comment]
Doubt that. In FB4 gbak code was seriously rewritten, making it possible to correctly process mentioned case. Porting fix to FB3 is far not trivial.
