### ISSUE TITLE
Error with FB 5 installer on Windows 7

### ISSUE THREAD

**Issue by WarmBooter** [FirebirdSQL/firebird#7724]
While trying to (full) install FB 5.0 32bits snapshot 1176 on a Windows 7 32bits VM and in the end of the installation I got this error:

"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

If there is some dependency missing, the installer should install it automatically. In previous Firebird versions, I never had to install anything manually to have a successful installation.

@reevespaul

**Comment by aafemt** [comment]
Windows 7 is not supported both Microsoft and Firebird.

**Comment by WarmBooter** [comment]
Microsoft doesn't officially support Windows 7 anymore, but if Firebird doesn't support it too, this should be documented somewhere (I found nothing in the release notes) and at least the installer should refuse to install on Windows 7 instead of doing a "corrupt install".

**Comment by WarmBooter** [comment]
After manually installing KB2999226, the Firebird installation completed with no errors, so probably the installer could at least:
- Install it automatically
- Ask the user to do that manually and interrupt the installation instead of raising errors

**Comment by hvlad** [comment]
> Windows 7 is not supported both Microsoft and Firebird.

Where you get such weird idea about Firebird ?

**Comment by mrotteveel** [comment]
> > Windows 7 is not supported both Microsoft and Firebird.
> 
> Where you get such weird idea about Firebird ?

To be honest, I also think that Firebird 5 should not support Windows 7.

**Comment by WarmBooter** [comment]
> > > Windows 7 is not supported both Microsoft and Firebird.
> > 
> > 
> > Where you get such weird idea about Firebird ?
> 
> To be honest, I also think that Firebird 5 should not support Windows 7.

Why? It seems that the only problem is the lacking of curt by default, which can be solved installing it. Lack of support for win 7 would officially exclude thousands of millions of network terminals still running on that version.

**Comment by aafemt** [comment]
Are these terminals run Firebird server instead of client only...?

**Comment by WarmBooter** [comment]
> Are these terminals run Firebird server instead of client only...?

Who knows? In Brazil there are still tons of windows 7 out there. I still see no reason to stop supporting it right now. Afaik, it doesn't requires any special code to be maintained, so it does not add any extra work to the team.

**Comment by reevespaul** [comment]
When the host O/S does not have the Windows 10 run time libraries installed then applications that require them will fail. This is not a windows 7 problem, as such. It applies to all versions of Windows released prior to Windows 10. And in normal use ( ie, where the user has regularly applied the latest updates from Microsoft ) this problem should not appear.

This link: http://support.microsoft.com/kb/KB2999226 explains all the operating systems affected.

Firebird installers, for 3, 4 and 5, should all fail under these  circumstances.

The exact error has not been included in the issue report but from a screen shot sent to me privately the error occurs during execution of instreg. Instreg requires the runtime libraries it was built with and they are installed during installation but they are obviously not available at the moment of instreg's execution. I'm surprised this error hasn't come up before.

More study of this issue is required. In the meantime I would suggest adding some sort of generic text to the release notes and the installation readme to warn users that installing Firebird on a system that is not up to date may fail with such an error and in such cases the user should install KB2999226 and retry the installation.

**Comment by asfernandes** [comment]
Statically building instreg does not solve it?

**Comment by reevespaul** [comment]
Maybe, but that would require a change in the build process, not the packaging.

And I've just checked the innosetup script. Instreg is executed after the installation of the firebird msvc runtime libraries. So it look as if even the msvc runtime msi has some sort of dependency that is resolved by installing KB2999226.

**Comment by reevespaul** [comment]
Or tb be more precise **the libraries installed** by the msvc runtime msi have some sort of dependency on other libraries.

**Comment by hvlad** [comment]
> the error occurs during execution of instreg

Why we still need instreg ? For what ?

**Comment by reevespaul** [comment]
As far as I understand it, instreg exists to just add a marker in the registry so that (theoretically) 3rd party applications can determine if firebird is installed and where it is installed. It has never been used by firebird itself - we just inherited it from InterBase 6.0. It has never caused any problems, which is probably why it is still there.

But I do not think the future of instreg is relevant to resolving this issue.  After instreg the installer calls instclient and then instsvc. If instreg fails it is unlikely that they will also fail for the same reason.

But the main question remains - why haven't we seen this error before? This section of the installer is unchanged for years - install msvc runtimes, execute the three inst*.exe files. 

I suspect the error (if any) is hidden by the way the msvc runtime install is set to "/norestart" and the msiexec log file is immediately deleted after install (by the system?)

**Comment by aafemt** [comment]
> As far as I understand it, instreg exists to just add a marker in the registry 
> so that (theoretically) 3rd party applications can determine if firebird is 
> installed and where it is installed.


No, it does Inno Setup itself.

**Comment by reevespaul** [comment]
This issue is in fact already documented (but poorly) in the installation_readme.txt. I shall improve it to include a reference to the KB article.

There has been a comment in the InnoSetup script since FB4.0 which has more info:

; As per the innosetup documentation:
;  "Change in default behavior: [Setup] section directive MinVersion now
;  defaults to 6.1sp1, so by default Setup will not run on Windows Vista or
;  on versions of Windows 7 and Windows Server 2008 R2 which have not been
;  updated. Setting MinVersion to 6.0 to allow Setup to run on Windows Vista
;  is supported but not recommended - Windows Vista doesn't support some of
;  Setup's security measures against potential DLL preloading attacks so these
;  have to be removed by the compiler if MinVersion is below 6.1 making your
;  installer less secure on all versions of Windows."
;
; This change _may_ be a problem for W2K8 R2. In any case Windows Vista and
; even Windows 7 are now deprecated and hopefully no production install of
; W2K8 R2 is unpatched. If necessary we can define 'support_legacy_windows' to
; roll back this new feature but users who need to deploy to what are now
; ancient versions of windows are advised to manually install Firebird 4.0 with
; the zip package.
