### ISSUE TITLE
Make it possible to handle attach errors in key holder plugin.

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7951]
In some cases (like encryption key entered by user in dialogue mode) it's very useful to be able to handle attach errors in key holder in order to be able to repeat with modified key value.

**Comment by AlexPeshkoff** [comment]
Solution ported from HQbird. Old key holders will proceed to work and compile as earlier.

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@

It's probably impossible to do a test for this ticket.
But indirectly it can be checked by following actions:

1) add into firebird.conf parameter ```KeyHolderPlugin = fbSampleKeyHolder```;
2) copy files  fbSampleKeyHolder.conf &  fbSampleKeyHolder.dll from %FB_HOME\examples\prebuilt\plugins\ to %FB_HOME\plugins\
2) run b/r of employee with specifying "-par <N>" where ```<N>``` for sure more than number of logical CPUs, e.g.:
```%FB_HOME%\gbak -b -m -g localhost:employee stdout | %FB_HOME%\gbak -rep -v -par 99 stdin localhost:C:\FB\60sS\examples\empbuild\tmp.fdb -z 1>C:\TEMP\tmprestore.log.tmp 2>&1```
3) get number of occurrences of string 'WARNING:' in the log:
```find /i /c "warning" C:\TEMP\tmprestore.log.tmp```

Output of 'find' command must be:
```------- C:\TEMP\tmprestore.log.tmp: 1```

PS.
Problem initially was encountered when test [tests/functional/tabloid/test_333be4bf.py](https://github.com/FirebirdSQL/firebird-qa/blob/master/tests/functional/tabloid/test_333be4bf.py) started failing since 6.0.0.213 (15.01.2024).
(line with "WARNING:" missed there).

**Comment by AlexPeshkoff** [comment]
Rather useless test. It checks correct error handling in remote client. That has nothing to do with ability to handle errors in key holder plugin.
