### ISSUE TITLE
Cascade delete error with empty constraint

### ISSUE THREAD

**Issue by alex7001d** [FirebirdSQL/firebird#7970]
We have databases that have been operating for more than 10 years. They went through Backup/Restore many times, migrated from 2.1 to 2.5, then to 3.0. They were damaged and restored.
Now in several of these databases on Firebird 2.5 I am observing a situation where cascade deletion does not work. There is a correct Foreign key, there are no triggers that would interfere with deletion.

An error appears like:
violation of FOREIGN KEY constraint "".
violation of FOREIGN KEY constraint "FK_TABLE_SLAVE_1" on table "TABLE_SLAVE".
Foreign key references are present for the record.
Problematic key value is ("ID" = 1).
------------------------------------------------------------------------------
SQLCODE: -530
SQLSTATE: 23000
GDSCODE: 335544466

I migrated the database via Backup/Restore to Firebird 3, Firebird 5, the situation is similar there. The same error is thrown.
In most databases with the same structure, the error does not occur.
If I delete the Foreign key and create it again, the error stops appearing.

Conducted research on system tables. It turned out that for Foreign key FK_TABLE_SLAVE_1 there are entries in RDB$CHECK_CONSTRAINTS, where CHECK_NNN is specified in RDB$TRIGGER_NAME. But there are no entries in RDB$TRIGGERS with such CHECK_NNN.
When the Foreign key is recreated, these entries appear in RDB$TRIGGERS and after that the error goes away.

Actually a question. Is it possible to make these entries in RDB$TRIGGERS appear during Backup/Restore?

A script that reproduces the situation (works well in Firebird 2.5, in higher versions an error occurs when deleting from RDB$TRIGGERS). If the database with tables from the demo script is migrated to Firebird 3/5, then an error will also appear when deleting.

[reproduce.txt](https://github.com/FirebirdSQL/firebird/files/13978195/reproduce.txt)

**Comment by hvlad** [comment]
> Actually a question. Is it possible to make these entries in RDB$TRIGGERS appear during Backup/Restore?

I don't think so. 

You have a broken database (some system triggers was deleted manually) and want to "fix" it by gbak. 
It doesn't work this way.
You need to re-create broken FK's before backup. It seems you already know the way how to find them.

As you already found, Firebird not allowed such dangerous changes of system tables anymore (since v3).
Thus, I don't see what else could be done at our side.

**Comment by alex7001d** [comment]
The database was corrupted and after it was repaired (FBFirstAid, gfix, B/R) it no longer had enough data in the service tables.
Of course, we did not delete this data ourselves. The post above deleting data is just an example of how to reproduce this problem.

Of course, we will recreate Foreign keys ourselves. It is simply surprising that Firebird does not restore its system objects on its own during Backup/Restore.

**Comment by hvlad** [comment]
> It is simply surprising that Firebird does not restore its system objects on its own during Backup/Restore.

Firebird can't put into backup what doesn't exists in system catalogue. 
Firebird can't restore from backup what wasn't put into it.

**Comment by aafemt** [comment]
On the other hand Firebird can put into backup single record about constraint with whole bunch of properties and restore it as a single constraint instead of dumb copying of every implementation detail that can be not actual for newer engine version (for example "any index key" that may need or not separate index and constraint definitions).
