### ISSUE TITLE
Hang when database with disconnect trigger using MON$ tables is shutting down

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7979]
When the following database:

SET SQL DIALECT 3; 

CREATE TABLE LOGGER (DET_TIME TIMESTAMP,
        AC INTEGER);

SET TERM ^ ;
CREATE TRIGGER LOGGER 
ACTIVE ON DISCONNECT POSITION 0 
as declare variable c int; begin select count(*) from mon$attachments into :c; insert into logger values(current_timestamp, :c); end ^
SET TERM ; ^

COMMIT WORK;

having at least one additional attachment is shutdown SS hangs.

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@

Bug could NOT be reproduced on Windows.
Bug can be reproduced only when appropriate code runs OUTSIDE current firebird-QA framework, i.e. directly from OS.
Because of that, test creates temporary .py script which is launched further using subprocess.run( [ sys.executable ...] ).
Confirmed problem on 6.0.0.219: 'gfix -shut full -force 0' hangs.
Checked on 6.0.0.244.
