### ISSUE TITLE
gbak v4 can't backup database in ODS <13

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#8003]
1. Run Firebird 3
2. Try to backup database in ODS12 using gbak v4 or v5:

```
firebird>gbak -b -g inet://database.fdb backup.fbk -z
gbak:gbak version WI-V5.0.1.1333 Firebird 5.0
gbak:    Version(s) for database "inet://database.fdb"
        Firebird/Windows/AMD/Intel/x64 (access method), version "WI-V3.0.11.33666 Firebird 3.0"
        Firebird/Windows/AMD/Intel/x64 (remote server), version "WI-V3.0.11.33666 Firebird 3.0/tcp (FireWork)/P15:C"
        Firebird/Windows/AMD/Intel/x64 (remote interface), version "WI-V5.0.1.1333 Firebird 5.0/tcp (FireWork)/P15:C"
        on disk structure version 12.0
gbak: ERROR:table id 51 is not defined
```

**Comment by hvlad** [comment]
Relation 51 is RDB$PUBLICATIONS

**Comment by mrotteveel** [comment]
Isn't that entirely expected?

**Comment by hvlad** [comment]
Yes, sure

**Comment by hmoffatt** [comment]
This scenario still doesn't seem to work for me on a recent Firebird 5.0.1 snapshot, with a 2.5.9 server; should it work?

$ /opt/firebird/bin/gbak -z -B localhost/3050:sessions sessions.fbk
gbak:gbak version LI-V5.0.1.1399 Firebird 5.0 77af75c
gbak:    Version(s) for database "localhost/3050:sessions"
	Firebird/Linux/AMD/Intel/x64 (access method), version "LI-V2.5.8.27089 Firebird 2.5"
	Firebird/Linux/AMD/Intel/x64 (remote server), version "LI-V2.5.8.27089 Firebird 2.5/tcp (dbtest1)/P12"
	Firebird/Linux/AMD/Intel/x64 (remote interface), version "LI-V5.0.1.1399 Firebird 5.0 77af75c/tcp (dbtest1)/P12"
	on disk structure version 11.2
gbak: ERROR:invalid request BLR at offset 50
gbak: ERROR:    data operation not supported
gbak:Exiting before completion due to errors

**Comment by hvlad** [comment]
This is completely different error, please create new issue and provide steps to reproduce.

**Comment by hmoffatt** [comment]
I've filed #8128. Thanks.
