### ISSUE TITLE
Query "WHERE A.NAME LIKE :NAME || '%'" does not use index on NAME field

### ISSUE THREAD

**Issue by dsonda** [FirebirdSQL/firebird#8322]
This query does not use the index on NAME field and use a natural plan:

SELECT A.ID, A.NAME
FROM PRODUCT A
WHERE A.NAME LIKE :NAME || '%'

**Comment by asfernandes** [comment]
Indices are chosen at prepare time, where the is no value for `:NAME`, that can start with `%`.
If you replace `LIKE` by `STARTING`, it could use.
Or use LIKE with constant instead of parameter: `LIKE 'Name%'`. In this case, Firebird will insert an implicit `STARTING WITH 'Name'` making it could use an index.

**Comment by dsonda** [comment]
This command is created by an ORM, so I'm trying to intercept and change to `STARTING WITH :NAME`, until the ORM fix.

**Comment by mrotteveel** [comment]
Duplicates #7912
